### ISSUE TITLE
Basic liquibase for DB

### ISSUE THREAD

**Issue by ballack44** [gyapeee/desertwind#15]

**Comment by gyapeee** [comment]
https://marcenschede.medium.com/spring-boot-using-liquibase-to-load-test-and-demo-data-a7f9810066bc
https://tillias.wordpress.com/2012/11/10/unit-testing-and-integration-testing-using-junit-liquibase-hsqldb-hibernate-maven-and-spring-framework/
https://www.baeldung.com/spring-jpa-test-in-memory-database
https://www.baeldung.com/liquibase-refactor-schema-of-java-app

**Comment by gyapeee** [comment]
https://javadeveloperzone.com/spring-boot/spring-boot-liquibase-example/
